services:
  - path: services/example
    name: example
    sdk:
      image: ghcr.io/tomusdrw/jammin-as-lan:main-6470f4f
      build: sh -c "npm install --no-audit --no-fund && npm run build"
      test: sh -c "npm install --no-audit --no-fund && npm test"
